
package view;

import java.awt.Color;
import java.awt.Image;

/**
 * Classe qui représente la fenêtre d'accueil du jeu.
 * @author thitchon
 */
public class Accueil extends javax.swing.JFrame {
    /**
     * Attribut static contenant l'instance de FenetreAppelante avec les données des autres fenêtres et les données de la partie en cours.
     * @attribute _fenetreAppelante
     */
    private static FenetreAppelante _fenetreAppelante;

    /**
     * Constructeur de la classe Accueil.
     * @param tw l'instance de la classe FenetreAppelante avec les données des autres fenêtres et les données du jeu
     */
    public Accueil(FenetreAppelante tw) {
        _fenetreAppelante = tw;
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.BLACK);

        this.setIconImage((new javax.swing.ImageIcon(getClass().getResource("/image/pimpMyRobotProjectIcon.jpg")).getImage()));
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jlb_titre = new javax.swing.JLabel();
        btn_suiv = new javax.swing.JButton();
        btn_didacticiel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_titre.setForeground(new java.awt.Color(255, 255, 255));
        jlb_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_titre.setText("<html>\n<style>\nh1{font-family: Impact, Helvetica, sans-serif; font-style: italic}\n</style>\n<body>\n<h1>PimpMyRobot</h1>\n</body>\n</html>");

        btn_suiv.setBackground(new java.awt.Color(255, 153, 0));
        btn_suiv.setText("<html>\n<style>\np{font-family: Helvetica, Arial, sans-serif;}\n</style>\n<body>\n<p>Commencer</p>\n</body>\n</html>");
        btn_suiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suivActionPerformed(evt);
            }
        });

        btn_didacticiel.setBackground(new java.awt.Color(255, 153, 0));
        btn_didacticiel.setText("<html>\n<style>\np{font-family: Helvetica, Arial, sans-serif;}\n</style>\n<body>\n<p>Didacticiel</p>\n</body>\n</html>");
        btn_didacticiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_didacticielActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jlb_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_didacticiel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suiv, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(355, 355, 355))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jlb_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_suiv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btn_didacticiel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    /**
     * Lance la nouvelle fenêtre (ici la fenêtre Lancement).
     * @param evt evenement déclancher par le clic sur le bouton
     */
    private void btn_suivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suivActionPerformed
        this.setVisible(false);
        _fenetreAppelante.getLancement().setVisible(true);
       //_fenetreAppelante.getBilan().recompense();
    }//GEN-LAST:event_btn_suivActionPerformed

    private void btn_didacticielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_didacticielActionPerformed
        this.setVisible(false);
        _fenetreAppelante.getDidacticiel().setVisible(true);
    }//GEN-LAST:event_btn_didacticielActionPerformed

    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Accueil.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Accueil.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLoggerAccueil.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Accueil.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new Accueil(_fenetreAppelante).setVisible(true);
                }
            });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_didacticiel;
    private javax.swing.JButton btn_suiv;
    private javax.swing.JLabel jlb_titre;
    // End of variables declaration//GEN-END:variables

}
