
package view;

import java.awt.Color;

import java.io.FileNotFoundException;
import java.io.FileReader;

import java.io.IOException;

import java.net.URI;
import java.net.URISyntaxException;

import java.nio.file.Path;
import java.nio.file.Paths;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author thitchon
 */
public class Didacticiel extends javax.swing.JFrame {
    /**
     * Attribut static contenant l'instance de TestView avec les données des autres fenêtres et les données du jeu.
     * @attribute static _testview
     */
    private static FenetreAppelante _fenetreAppelante;

    private int iterator=0;

    private String path ="";

    /** Creates new form Didacticiel */
    public Didacticiel(FenetreAppelante tw) {
        _fenetreAppelante = tw;
        initComponents();
        try {
            URI u = FenetreAppelante.class.getResource(".").toURI();
            Path p = Paths.get(u);
            path = p.getParent().getParent().getParent().resolve("ressources/JSON/didacticiel.json").toString();
        } catch (URISyntaxException e) {
            System.out.println(e);
        }
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(20, 20, 20));
        jpnTx_texte.setOpaque(true);
        jpnTx_texte.setBackground(new Color(40, 40, 40));
        prochainnePage(iterator);
        jpnTx_texte.setEditable(false);

        this.setIconImage((new javax.swing.ImageIcon(getClass().getResource("/image/pimpMyRobotProjectIcon.jpg"))).getImage());
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        btn_suiv = new javax.swing.JButton();
        btn_prec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpnTx_texte = new javax.swing.JTextPane();
        _label_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_suiv.setBackground(new java.awt.Color(0, 51, 255));
        btn_suiv.setForeground(new java.awt.Color(255, 255, 255));
        btn_suiv.setText("Suivant");
        btn_suiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suivActionPerformed(evt);
            }
        });

        btn_prec.setBackground(new java.awt.Color(0, 0, 255));
        btn_prec.setForeground(new java.awt.Color(255, 255, 255));
        btn_prec.setText("Pr�c�dent");
        btn_prec.setToolTipText("");
        btn_prec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_precActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jpnTx_texte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(_label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_prec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(btn_suiv, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prec, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void btn_suivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suivActionPerformed
        this.iterator+=1;
        prochainnePage(iterator);
    }//GEN-LAST:event_btn_suivActionPerformed

    private void btn_precActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_precActionPerformed
        this.iterator-=1;
        prochainnePage(iterator);
    }//GEN-LAST:event_btn_precActionPerformed


    public void prochainnePage(int index){
        this.iterator = index;
        Object obj;
        String text ="";
        String image ="";
        try {
            JSONObject jo  = (JSONObject) new JSONParser().parse(new FileReader(path));

            JSONArray ja = (JSONArray) jo.get("content");
            for(int i = 0; i<ja.size();i++){
                JSONObject ob = (JSONObject) ja.get(i);
                Integer id = Integer.valueOf(String.valueOf(ob.get("id")));
                if(id==index){
                text = ob.get("text").toString();
                image= ob.get("image").toString();
                }
            }
        }
        catch (FileNotFoundException e) {
                    System.out.println(e);
                    } catch (IOException e){
                    System.out.println((e));

                    } catch (ParseException e) {
                    System.out.println(e);
                }
        switch(iterator){
                case 0:
                    this.btn_prec.setVisible(false);
                    this.jpnTx_texte.setText(text);
                    this._label_image.setIcon(new ImageIcon(getClass().getResource(image)));
                    break;
                case 1:
                    this.btn_prec.setVisible(true);
                    this.jpnTx_texte.setText(text);
                    this._label_image.setIcon(new ImageIcon(getClass().getResource(image)));
                    break;
                case 2:
                    this.jpnTx_texte.setText(text);
                    this.btn_suiv.setText("Suivant");
                    this._label_image.setIcon(new ImageIcon(getClass().getResource(image)));
                    break;
                case 3:
                    this.jpnTx_texte.setText(text);
                    this.btn_suiv.setText("Suivant");
                    this._label_image.setIcon(new ImageIcon(getClass().getResource(image)));
                    break;
                case 4:
                    this.jpnTx_texte.setText(text);
                    this._label_image.setIcon(new ImageIcon(getClass().getResource(image)));
                    this.btn_suiv.setText("Fin du tutoriel");
                    break;

                case 5:
                    this.iterator = 0;
                    this.setVisible(false);
                    _fenetreAppelante.getLancement().setVisible(true);
                }



    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Didacticiel.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Didacticiel.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Didacticiel.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Didacticiel.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new Didacticiel(_fenetreAppelante).setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _label_image;
    private javax.swing.JButton btn_prec;
    private javax.swing.JButton btn_suiv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jpnTx_texte;
    // End of variables declaration//GEN-END:variables

}
