
package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 * Classe qui représente l'affichage de toutes les règles possible de choisir pour le joueur.
 * @author meya
 */
public class FenetreRegle extends javax.swing.JFrame {
    /**
     * Attribut static contenant l'instance de FenetreAppelante avec les données des autres fenêtres et les données du jeu.
     * @attribute static _fenetreAppelante
     */
    private static FenetreAppelante _fenetreAppelante;

    /**
     * Panel contenant toutes les règles du jeu que le joueur peut choisir.
     * @attribute _panelRegle
     */
    private JPanel _panelRegle;

    /**
     * Panel contenant les règles choisies par le joueur, triée par ordre croissant des poids des règles.
     * @attribute _panelChoix
     */
    private JPanel _panelChoix;

    /**
     * Constructeur de la classe FenetreRegle.
     * @param tw l'instance de la classe FenetreAppelante avec les données des autres fenêtres et les données du jeu
     */
    public FenetreRegle(FenetreAppelante tw)  {
        _fenetreAppelante = tw;
        _panelRegle = new JPanel();
        BoxLayout boxlayout1 = new BoxLayout(_panelRegle, BoxLayout.Y_AXIS);
        _panelRegle.setLayout(boxlayout1);
        _panelChoix = new JPanel();
        BoxLayout boxlayout2 = new BoxLayout(_panelChoix, BoxLayout.Y_AXIS);
        _panelChoix.setLayout(boxlayout2);
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        _panelRegle.setBackground(new Color(20, 20, 20));
        _panelChoix.setBackground(new Color(20, 20, 20));
        this.setLocationRelativeTo(null);
        Border lineborder = BorderFactory.createLineBorder(new Color(20, 20, 20), 1);
        Border borderRegle = BorderFactory.createTitledBorder(lineborder, "Règles à séléctionner:", TitledBorder.LEFT,TitledBorder.TOP, new Font("Arial",Font.PLAIN, 20), Color.WHITE);
        Border borderChoix = BorderFactory.createTitledBorder(lineborder, "Règles choisies:", TitledBorder.LEFT,TitledBorder.TOP, new Font("Arial",Font.PLAIN, 20), Color.WHITE);
        _panelRegle.setBorder(borderRegle);
        _panelChoix.setBorder(borderChoix);
        grpbox_regles.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        grpbox_regles.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        refresh();

        this.setIconImage((new javax.swing.ImageIcon(getClass().getResource("/image/pimpMyRobotProjectIcon.jpg"))).getImage());
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jbt_suiv = new javax.swing.JButton();
        grpbox_regles = new javax.swing.JScrollPane();
        grpBox_choix = new javax.swing.JScrollPane();
        jlb_titre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbt_suiv.setBackground(new java.awt.Color(0, 51, 255));
        jbt_suiv.setForeground(new java.awt.Color(255, 255, 255));
        jbt_suiv.setText("Page suivante");
        jbt_suiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_suivMouseClicked(evt);
            }
        });

        grpbox_regles.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                grpbox_reglesPropertyChange(evt);
            }
        });

        jlb_titre.setForeground(new java.awt.Color(255, 153, 0));
        jlb_titre.setText("<html>\n<style>\nh1{font-style: italic;}\n</style>\n<body>\n<h1>A vous de choisir vos règles!</h1>\n</body>\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(jlb_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grpbox_regles, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grpBox_choix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_suiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grpBox_choix, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(jbt_suiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(grpbox_regles))
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void grpbox_reglesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_grpbox_reglesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_grpbox_reglesPropertyChange

    /**
     * Ajoute les règles choisies par le joueur à son robot puis lance la fenêtre suivante (ici la fenêtre Situation).
     */
    private void jbt_suivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_suivMouseClicked
    _fenetreAppelante.getGame().getRobot().getListRegles().clear();
        this.setVisible(false);
            for(Component c:_panelChoix.getComponents()){
                if(c instanceof javax.swing.JLabel){
                    javax.swing.JLabel l = (javax.swing.JLabel)c;

                    for(model.Regle r:_fenetreAppelante.getGame().getTouteRegles()){
                        if(l.getText().toString().equals(r.getIntitule())){
                            _fenetreAppelante.getGame().addRegleRobot(r);
                        }
                    }
                }
            }
        _fenetreAppelante.getHiera().refresh();
        _fenetreAppelante.getHiera().setVisible(true);
    }//GEN-LAST:event_jbt_suivMouseClicked

    /**
     * Ajoute la règle coché par le joueur au _panelChoix ou bien supprime du _panelChoix la règle décoché par le joueur.
     * @param chk le JCheckBox contenant l'intitulé de la règle
     */
    private void addregle(JCheckBox chk){
        if(chk.isSelected()){
            chk.setForeground(new Color(255, 153, 0));
            JLabel l = new JLabel(chk.getText());
            l.setForeground(new Color(255, 153, 0));
            _panelChoix.add(l);
        }
        else{
            chk.setForeground(Color.WHITE);
            for(Component c: _panelChoix.getComponents()){
                if(c instanceof JLabel){
                    JLabel l = (JLabel)c;
                    if(l.getText()==chk.getText()){
                        _panelChoix.remove(l);
                    }
                }
            }
        }
        grpBox_choix.setViewportView(_panelChoix);
    }

    /**
     * Ajoute toutes les règles du jeu au panel _panelRegle.
     */
    public void refresh() {
        /*this._panelRegle.removeAll();
        this._panelChoix.removeAll();
        _fenetreAppelante.getGame().getRobot().getListRegles().clear();*/
        for (model.Regle r : _fenetreAppelante.getGame().getTouteRegles()){
            JCheckBox chk = new JCheckBox();
            chk.setText(r.getIntitule());
            chk.setForeground(Color.WHITE);
            chk.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent itemEvent) {
                    addregle(chk);
                }
            });
            if(r.getID() == 2 || r.getID() == 3) {

                chk.setEnabled(false);
                chk.setSelected(true);
            }
            _panelRegle.add(chk);
            _panelRegle.add(Box.createRigidArea(new Dimension(1, 5)));
            /*for(Component c: grpbox_regles.getComponents()){
                if(c instanceof JCheckBox){
                    JCheckBox l = (JCheckBox)c;
                        for(model.Regles regle: testview.getGame().getRobot().getRegles()){
                            if(l.getText()==regle.getIntitule()){
                                l.setSelected(true);
                            }
                        }
                }
                testview.getGame().removeRegles();
            }*/
        }
        grpbox_regles.setViewportView(_panelRegle);
    }

    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ViewRegle.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ViewRegle.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ViewRegle.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ViewRegle.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run()  {
                    new ViewRegle(_fenetreAppelante).setVisible(true);
                }
            });
    }*/



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane grpBox_choix;
    private javax.swing.JScrollPane grpbox_regles;
    private javax.swing.JButton jbt_suiv;
    private javax.swing.JLabel jlb_titre;
    // End of variables declaration//GEN-END:variables

}
